// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJWoWr_VwF1SU5GjqycCK7ebSt8sB-qyM',
    appId: '1:408984364299:web:b4da1474e4899b8daf6e0e',
    messagingSenderId: '408984364299',
    projectId: 'cashflowiq-e10ac',
    authDomain: 'cashflowiq-e10ac.firebaseapp.com',
    storageBucket: 'cashflowiq-e10ac.firebasestorage.app',
    measurementId: 'G-4FD9V5RD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMSHc4lOs6ts_LQSMz9pc9r0CI4r23Ae8',
    appId: '1:408984364299:android:1721ea978d0999ddaf6e0e',
    messagingSenderId: '408984364299',
    projectId: 'cashflowiq-e10ac',
    storageBucket: 'cashflowiq-e10ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2UuOEzLjQ06KivqDW6OfPgQ8bJPHqU4',
    appId: '1:408984364299:ios:d0ba02ef102e272baf6e0e',
    messagingSenderId: '408984364299',
    projectId: 'cashflowiq-e10ac',
    storageBucket: 'cashflowiq-e10ac.firebasestorage.app',
    iosBundleId: 'com.example.cashflowiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc2UuOEzLjQ06KivqDW6OfPgQ8bJPHqU4',
    appId: '1:408984364299:ios:d0ba02ef102e272baf6e0e',
    messagingSenderId: '408984364299',
    projectId: 'cashflowiq-e10ac',
    storageBucket: 'cashflowiq-e10ac.firebasestorage.app',
    iosBundleId: 'com.example.cashflowiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJWoWr_VwF1SU5GjqycCK7ebSt8sB-qyM',
    appId: '1:408984364299:web:8bfb5cf289b1d15caf6e0e',
    messagingSenderId: '408984364299',
    projectId: 'cashflowiq-e10ac',
    authDomain: 'cashflowiq-e10ac.firebaseapp.com',
    storageBucket: 'cashflowiq-e10ac.firebasestorage.app',
    measurementId: 'G-7MFS2R18Z1',
  );
}
